### ISSUE TITLE
Flag the usage of wpurl

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-scanner#233]
`get_bloginfo( 'wpurl' );` should not be used - use `home_url()` instead, as the latter returns the mapped domain if available, and is more standardized.

**Comment by sboisvert** [comment]
We should probably also flag site_url as that's pretty much the same thing and 99% of the time people want home_url

**Comment by nickdaugherty** [comment]
:+1: for flagging `site_url()` - I'm surprised it isn't already flagged anywhere. That should be a warning.

I realized `wpurl` is actually checked for in `DeprecatedParametersCheck` - https://github.com/Automattic/vip-scanner/blob/c8f9f1d7972ce919589994482a934f1631ae73d3/vip-scanner/checks/DeprecatedParametersCheck.php#L16

Unfortunately, that check isn't enabled on VIP scans (but it probably should be).

**Comment by fklein-lu** [comment]
There are actually three checks dealing with deprecated code: parameters, functions and also constants. I think it would make sense to include all three checks into the VIP review type.

**Comment by nickdaugherty** [comment]
:+1: I think not including those checks up until this point has been an oversight.
