### ISSUE TITLE
Add nudge for add_theme_support( 'jetpack-responsive-videos' ) in themes

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/vip-scanner#235]
It would be nice to have a nudge for themes to `add_theme_support( 'jetpack-responsive-videos' );` to their theme.

This is something the Theme Team includes in all the themes we develop for WorfPress.com. It would be great to have that reminder for Premium and VIP themes.

**Comment by fklein-lu** [comment]
This is already implemented, see `JetpackCheck.php`.

Currently the check is only run when the theme uses the _responsive_ tag in `style.css`. We could probably remove this extra check, since all WP.com themes are now responsive.

**Comment by danielwrobert** [comment]
If I'm understanding this correctly, the scanner is currently showing this as a warning and not as a requirement - https://github.com/Automattic/vip-scanner/blob/81f97b7d46311eaf047c13bdefb0cefca50e0324/vip-scanner/checks/JetpackCheck.php#L34

Recently we have decided to shift this issue as a requirement (see first item under Code) - https://developer.wordpress.com/themes/

I can submit a PR for this, I just thought I'd add it to the conversation here as well. :)

**Comment by fklein-lu** [comment]
:+1: for a PR.

**Comment by fklein-lu** [comment]
Thanks! :+1:

**Comment by danielwrobert** [comment]
Anytime! :)
