### ISSUE TITLE
Error when checking for sanitization in add_setting

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/vip-scanner#250]
I have been getting the following error, however all of my add_setting calls have sanitization:

`Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.`

After a bit of searching I found that the error is because I had a semi-colon in a string in the default properties. It looked like this:

	$wp_customize->add_setting( 'showcase_title_projects', array(
		'default' => __( 'Recent Projects &rsaquo;', 'showcase' ),
		'capability' => 'edit_theme_options',
		'sanitize_callback' => 'esc_html',
	) );

Removing the semi-colon fixed the issue.

**Comment by fklein-lu** [comment]
This is indeed a bug related to the regular expression used to verify the presence of a callback. This should be solved when the test is moved over to using the PHP Analyzer.
