### ISSUE TITLE
Incorrectly flags existing WordPress functions in Undefined Function Check

### ISSUE THREAD

**Issue by lancewillett** [Automattic/vip-scanner#27]
Example screenshot: 
![function-in-core](https://f.cloud.github.com/assets/66797/1431105/1a99fb42-40ca-11e3-967d-6de5228b5744.png)

When running Undefined Function Check on Twenty Fourteen with core WP trunk.

The function exists in core, however: http://core.trac.wordpress.org/browser/trunk/src/wp-includes/class-wp-customize-manager.php#L997

**Comment by fklein-lu** [comment]
I can't replicate with the current version of the scanner, so I'll close this.
