### ISSUE TITLE
False Positive: vip-init.php was not required

### ISSUE THREAD

**Issue by hardlyneutral** [Automattic/vip-scanner#49]
I'm getting a false positive with the new version of the VIP Scanner after updating: vip-init.php was not required

These are the first few lines of my functions.php file:

<?php

// Init WP.com VIP environment 
require_once( WP_CONTENT_DIR . '/themes/vip/plugins/vip-init.php' );

**Comment by mdrovdahl** [comment]
Found another false positive:

functions.php:

``` php
vagrant@vip:~$ grep -n2 vip-init.php /srv/www/wp-content/themes/vip/cox-rare-kiro/functions.php 
11- * Init WP.com VIP environment
12- */
13:require_once WP_CONTENT_DIR . '/themes/vip/plugins/vip-init.php';
14-
15-/**
```
